### ISSUE TITLE
List of monsters with descriptions?

### ISSUE THREAD

**Issue by Skrell** [TheBlueSavior/Project-Malice#1]
Any chance you have documented a list of monsters with pics and descriptions?  I've been REALLY enjoying your MOD but have seen some strange behavior and wasn't sure if it was the correct monster behavior or not.

**Comment by TheBlueSavior** [comment]
I have an unfinished bestiary on the discord, but other obligations have been getting in the way of me finishing it or publishing it elsewhere. If you describe the monster to me and the issue I'll probably know which one you're talking about.

**Comment by Skrell** [comment]
It looked like an all black marine that moved in and out of walls with no clipping?

**Comment by TheBlueSavior** [comment]
> It looked like an all black marine that moved in and out of walls with no clipping?

That sounds like intended behavior! Some rarer enemies are more anomalous than others.
