### ISSUE TITLE
VM abort caused when shooting a Gazer

### ISSUE THREAD

**Issue by BiggieYosh** [TheBlueSavior/Project-Malice#2]
There's a chance that you get a VM abort when shooting a Gazer, was using GZdoom 4.11.3, here is the message that shows up

![Screenshot_Doom_20240201_211242](https://github.com/TheBlueSavior/Project-Malice/assets/157257780/83812dcd-c285-4a76-9e4b-15a727faac8b)

**Comment by TheBlueSavior** [comment]
Thanks for reporting this! I think Bugsie was able to resolve this issue with his fix commit, so I'll mark this issue as closed for now. If you see it pop up again, please open another issue or let us know in some capacity.
