### ISSUE TITLE
abort

### ISSUE THREAD

**Issue by Rowsol** [TheBlueSavior/Project-Malice#5]
![Screenshot_Doom_20240507_224815](https://github.com/TheBlueSavior/Project-Malice/assets/35880360/116a23f6-7132-441d-8024-4ddb31e5f9cb)

Many hours behind this mod and this is the first I'm seeing this. 
Using 4.11.3 with some other mods.

**Comment by TheBlueSavior** [comment]
I think we just fixed it, thanks for reporting this! If you ever see this again or any other crash, please make another issue.
